@startuml DomainModel
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods

class Client {
    - name
    - email 
    - phone
    - address
    - password
}

class Account {
    - password
    - username
    - accountname
    - client
    - balance
    - type
    - openDate
    - status
}

class Transfer {
    - originAccount
    - destinyAccount
    - value
    - date
    - status
    - description
}

class Transaction {
    - account
    - type
    - value
    - date
    - status
    - description
}

class TransferHistory {
    - account
    - transfers
    - dataInitial
    - dataFinal
}

Client "1"-"*" Account
Account "*"-"*" Transfers
Account "*"-"1" TransferHistory
Transfers "*"-"1" TransferHistory

@enduml
