@startuml LogicalView

package View {
}

package natwise {
    [Models]
    [Controllers]
    [DataManagement]
}

package Supabase {
}

View - Models : HTTP request
Models - Controllers : Process Requests
Conrtollers - DataManagement : Persist Data
DataManagement - Supabase: Save Data

@enduml
