@startuml LogicalView

package View {
}

package natwise {
component "Auth Service" as authService
component "Account Service" as accountService
component "Transfer Service" as transferService
component "Transaction Service" as transactionService
component "History Service" as historyService
}

package Supabase {
}

View -- natwise : HTTP request
natwise - Supabase: Management Data

@enduml
